"""Human-approved hand-off controller for the IBM Bob multi-agent workflow.

This tool does not impersonate IBM Bob or switch its modes. It verifies the
evidence produced by one stage, requires a named human approval, and creates an
auditable ticket telling the team exactly which Bob mode to select next.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Callable


STAGES = ("research", "coding", "review", "testing", "debug", "docs")


@dataclass(frozen=True)
class Gate:
    source: str
    target: str
    check: Callable[[Path], tuple[bool, str]]
    input_files: tuple[str, ...]
    output_file: str
    bob_mode: str


def _read(root: Path, relative_path: str) -> str:
    path = root / relative_path
    return path.read_text(encoding="utf-8") if path.exists() else ""


def _exists(relative_path: str, description: str) -> Callable[[Path], tuple[bool, str]]:
    def check(root: Path) -> tuple[bool, str]:
        present = (root / relative_path).is_file()
        return present, description if present else f"Missing required artifact: {relative_path}"

    return check


def _review_approved(root: Path) -> tuple[bool, str]:
    report = _read(root, "review_report.md")
    passed = "## Verdict: APPROVED" in report
    return passed, "Review verdict is APPROVED" if passed else "Review report is not APPROVED"


def _tests_passed(root: Path) -> tuple[bool, str]:
    report = _read(root, "test_report.md")
    passed = "**PASS — ready to merge.**" in report and "| Failed | 0" in report
    return passed, "Test report records PASS with zero failures" if passed else "Test report does not record a passing run"


def _tests_failed(root: Path) -> tuple[bool, str]:
    report = _read(root, "test_report.md")
    failed = "**FAIL" in report
    return failed, "Test report records FAIL" if failed else "Debug hand-off is allowed only after a test failure"


GATES = (
    Gate("research", "coding", _exists("design_brief.md", "Design brief is available"), ("docs/scope.md", "design_brief.md"), "app/", "Coding Agent"),
    Gate("coding", "review", _exists("app/main.py", "Application implementation is available"), ("design_brief.md", "app/main.py"), "review_report.md", "Review Agent"),
    Gate("review", "testing", _review_approved, ("design_brief.md", "review_report.md", "app/"), "app/test_*.py and test_report.md", "Testing Agent"),
    Gate("testing", "docs", _tests_passed, ("design_brief.md", "review_report.md", "test_report.md"), "app/README.md and docs/demo-script.md", "Pitch/Docs Agent"),
    Gate("testing", "debug", _tests_failed, ("design_brief.md", "test_report.md", "app/"), "debug_report.md", "Debug Agent"),
    Gate("debug", "coding", _exists("debug_report.md", "Debug diagnosis is available"), ("design_brief.md", "debug_report.md", "test_report.md"), "app/", "Coding Agent"),
)


def find_gate(source: str, target: str) -> Gate | None:
    return next((gate for gate in GATES if gate.source == source and gate.target == target), None)


def status_rows(root: Path) -> list[tuple[str, bool, str]]:
    checks = {
        "research": _exists("design_brief.md", "design brief exists"),
        "coding": _exists("app/main.py", "application implementation exists"),
        "review": _review_approved,
        "testing": _tests_passed,
        "debug": _exists("debug_report.md", "debug diagnosis exists"),
        "docs": _exists("docs/demo-script.md", "demo script exists"),
    }
    return [(stage, *checks[stage](root)) for stage in STAGES]


def write_status(root: Path) -> Path:
    workflow_dir = root / "docs" / "workflow"
    workflow_dir.mkdir(parents=True, exist_ok=True)
    rows = status_rows(root)
    lines = [
        "# Workflow Status",
        "",
        "Generated by `workflow/handoff_controller.py status`. This file is a snapshot; the JSONL hand-off log is the audit trail.",
        "",
        "| Stage | Gate status | Evidence |",
        "|---|---|---|",
    ]
    for stage, passed, message in rows:
        lines.append(f"| {stage.title()} | {'READY' if passed else 'BLOCKED'} | {message} |")
    lines.extend([
        "",
        "## Permitted transitions",
        "",
        *[f"- `{gate.source}` → `{gate.target}`" for gate in GATES],
        "",
        "A transition requires a successful evidence check and a named human approver.",
    ])
    path = workflow_dir / "status.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def create_handoff(root: Path, gate: Gate, approved_by: str) -> tuple[Path, dict[str, str]]:
    passed, message = gate.check(root)
    if not passed:
        raise ValueError(message)

    workflow_dir = root / "docs" / "workflow"
    workflow_dir.mkdir(parents=True, exist_ok=True)
    record = {
        "timestamp_utc": datetime.now(UTC).isoformat(),
        "source": gate.source,
        "target": gate.target,
        "approved_by": approved_by,
        "evidence": message,
        "bob_mode": gate.bob_mode,
        "input_files": ", ".join(gate.input_files),
        "expected_output": gate.output_file,
    }
    log = workflow_dir / "handoff-log.jsonl"
    with log.open("a", encoding="utf-8") as file:
        file.write(json.dumps(record) + "\n")
    return log, record


def print_ticket(record: dict[str, str]) -> None:
    print("HANDOFF APPROVED")
    print(f"Next IBM Bob mode: {record['bob_mode']}")
    print(f"Approved by: {record['approved_by']}")
    print(f"Evidence: {record['evidence']}")
    print(f"Read: {record['input_files']}")
    print(f"Expected output: {record['expected_output']}")
    print("Action: select the stated Bob mode and give it the listed inputs. The approval is logged.")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Guarded hand-offs for the IBM Bob agent workflow")
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("status", help="validate evidence and write docs/workflow/status.md")
    handoff = subparsers.add_parser("handoff", help="approve and log one permitted transition")
    handoff.add_argument("source", choices=STAGES)
    handoff.add_argument("target", choices=STAGES)
    handoff.add_argument("--approved-by", required=True, help="name of the human approving this transition")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = args.repo_root.resolve()
    if args.command == "status":
        path = write_status(root)
        print(f"Workflow status written to {path.relative_to(root)}")
        return 0

    gate = find_gate(args.source, args.target)
    if gate is None:
        print(f"Blocked: {args.source} → {args.target} is not a permitted transition.")
        return 2
    try:
        _, record = create_handoff(root, gate, args.approved_by)
    except ValueError as error:
        print(f"Blocked: {error}")
        return 1
    print_ticket(record)
    write_status(root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
